# Register User

POST http://localhost:3333/users
Content-Type: application/json 

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "123456"
}

### Authenticate

POST http://localhost:3333/sessions
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "123456"
}


### Get User Profile

GET http://localhost:3333/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTI4NzkwYS1lOGZlLTRmNzEtYTJkZi0wNDUyYjc0MmQ1NDQiLCJpYXQiOjE3MDM2MzM2MDF9.AFkBBlUUbwmAjkuw0hBnDXatb6IAaFKJ1UIJZxoSjzA


### Create gym

POST http://localhost:3333/gyms
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTI4NzkwYS1lOGZlLTRmNzEtYTJkZi0wNDUyYjc0MmQ1NDQiLCJpYXQiOjE3MDM2MzM2MDF9.AFkBBlUUbwmAjkuw0hBnDXatb6IAaFKJ1UIJZxoSjzA

{
    "title" : "JavaSript Academy",
    "description": "The academy who ever be created",
    "latitude": -22.19283719823,
    "longitude": -44.1231231235,
    "phone": "14996246309"
}